
services:
  user:
    build: ./user
    env_file:
      - ./user/.env
    networks:
      infra-shared:
        ipv4_address: ${USER_IP_ADDRESS}
    volumes:
      - ./resolv.conf:/etc/resolv.conf:ro

  chat:
    build: ./chat
    env_file:
      - ./chat/.env
    networks:
      infra-shared:
        ipv4_address: ${CHAT_IP_ADDRESS}
    volumes:
      - ./resolv.conf:/etc/resolv.conf:ro
    depends_on:
      - user

  email:
    build: ./email
    env_file:
      - ./email/.env
    networks:
      infra-shared:
        ipv4_address: ${EMAIL_IP_ADDRESS}

    depends_on:
      - user

networks:

  infra-shared:
    external: true