
services:
  user:
    build: ./user
    env_file:
      - ./user/.env
    networks:
      - app-network


  chat:
    build: ./chat
    env_file:
      - ./chat/.env
    networks:
      - app-network
    depends_on:
      - user

  email:
    build: ./email
    env_file:
      - ./email/.env
    networks:
      - app-network

    depends_on:
      - user

networks:
  app-network:
    driver: bridge